import { db } from "@workspace/db";
import { clinicsTable, offersTable, appointmentsTable, discountsTable, patientsTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(appointmentsTable);
  await db.delete(offersTable);
  await db.delete(discountsTable);
  await db.delete(patientsTable);
  await db.delete(clinicsTable);

  // Seed clinics
  const clinics = await db.insert(clinicsTable).values([
    {
      name: "Ahmed Al-Saleh Medical Center",
      nameAr: "مركز أحمد الصالح الطبي",
      specialty: "General Medicine",
      specialtyAr: "طب عام",
      phone: "+968 2234 5678",
      email: "info@ahmed-medical.om",
      address: "Al Qurum, Muscat",
      addressAr: "القرم، مسقط",
      city: "مسقط",
      openHours: "السبت - الخميس: 8 ص - 10 م",
      rating: 4.8,
      isActive: true,
      totalPatients: 342,
      pointsPerVisit: 150,
      descriptionAr: "مركز طبي متكامل يقدم خدمات الرعاية الأولية والمتخصصة",
      description: "Comprehensive medical center offering primary and specialized care",
    },
    {
      name: "Al-Shifa Dental Clinic",
      nameAr: "عيادة الشفاء للأسنان",
      specialty: "Dentistry",
      specialtyAr: "طب الأسنان",
      phone: "+968 2245 6789",
      email: "contact@alshifa-dental.om",
      address: "Ruwi, Muscat",
      addressAr: "الروي، مسقط",
      city: "مسقط",
      openHours: "الأحد - الخميس: 9 ص - 9 م",
      rating: 4.6,
      isActive: true,
      totalPatients: 218,
      pointsPerVisit: 120,
      descriptionAr: "عيادة أسنان متخصصة بأحدث التقنيات",
      description: "Specialized dental clinic with the latest technologies",
    },
    {
      name: "Royal Physiotherapy Center",
      nameAr: "مركز رويال للعلاج الطبيعي",
      specialty: "Physiotherapy",
      specialtyAr: "علاج طبيعي",
      phone: "+968 2256 7890",
      email: "royal@physio.om",
      address: "Seeb, Muscat",
      addressAr: "السيب، مسقط",
      city: "مسقط",
      openHours: "السبت - الأربعاء: 7 ص - 11 م",
      rating: 4.9,
      isActive: true,
      totalPatients: 156,
      pointsPerVisit: 200,
      descriptionAr: "مركز متخصص في العلاج الطبيعي وإعادة التأهيل",
      description: "Specialized center for physiotherapy and rehabilitation",
    },
    {
      name: "Oman Eye Institute",
      nameAr: "معهد عيون عُمان",
      specialty: "Ophthalmology",
      specialtyAr: "طب العيون",
      phone: "+968 2267 8901",
      email: "info@omaneye.om",
      address: "Bawshar, Muscat",
      addressAr: "بوشر، مسقط",
      city: "مسقط",
      openHours: "السبت - الخميس: 8 ص - 8 م",
      rating: 4.7,
      isActive: true,
      totalPatients: 289,
      pointsPerVisit: 180,
      descriptionAr: "معهد متخصص في أمراض وجراحة العيون",
      description: "Specialized institute for eye diseases and surgery",
    },
    {
      name: "Wellness Family Clinic",
      nameAr: "عيادة ويلنس العائلية",
      specialty: "Family Medicine",
      specialtyAr: "طب الأسرة",
      phone: "+968 2278 9012",
      email: "wellness@family.om",
      address: "Al Khoud, Muscat",
      addressAr: "الخوض، مسقط",
      city: "مسقط",
      openHours: "يومياً: 8 ص - 12 م",
      rating: 4.5,
      isActive: true,
      totalPatients: 198,
      pointsPerVisit: 100,
      descriptionAr: "عيادة عائلية شاملة لجميع الاحتياجات الصحية",
      description: "Comprehensive family clinic for all health needs",
    },
  ]).returning();

  // Seed offers
  await db.insert(offersTable).values([
    {
      clinicId: clinics[0].id,
      title: "Full Health Checkup",
      titleAr: "فحص صحي شامل",
      description: "Complete health screening including blood tests, ECG, and doctor consultation",
      descriptionAr: "فحص صحي شامل يشمل تحاليل الدم والقلب واستشارة الطبيب",
      originalPrice: 85,
      discountedPrice: 55,
      pointsRequired: 500,
      category: "فحوصات",
      isFeatured: true,
      isActive: true,
      expiryDate: "2026-06-30",
      usageCount: 45,
    },
    {
      clinicId: clinics[1].id,
      title: "Teeth Cleaning & Whitening",
      titleAr: "تنظيف وتبييض الأسنان",
      description: "Professional dental cleaning and whitening session",
      descriptionAr: "جلسة تنظيف وتبييض احترافي للأسنان",
      originalPrice: 120,
      discountedPrice: 80,
      pointsRequired: 800,
      category: "أسنان",
      isFeatured: true,
      isActive: true,
      expiryDate: "2026-07-31",
      usageCount: 28,
    },
    {
      clinicId: clinics[2].id,
      title: "10 Physiotherapy Sessions",
      titleAr: "10 جلسات علاج طبيعي",
      description: "Package of 10 physiotherapy sessions for chronic pain relief",
      descriptionAr: "باقة 10 جلسات علاج طبيعي لعلاج الآلام المزمنة",
      originalPrice: 250,
      discountedPrice: 180,
      pointsRequired: 1500,
      category: "علاج طبيعي",
      isFeatured: false,
      isActive: true,
      expiryDate: "2026-08-31",
      usageCount: 12,
    },
    {
      clinicId: clinics[3].id,
      title: "Laser Eye Examination",
      titleAr: "فحص العين بالليزر",
      description: "Comprehensive laser eye examination with detailed report",
      descriptionAr: "فحص شامل للعين بالليزر مع تقرير مفصل",
      originalPrice: 95,
      discountedPrice: 65,
      pointsRequired: 600,
      category: "عيون",
      isFeatured: true,
      isActive: true,
      expiryDate: "2026-09-30",
      usageCount: 34,
    },
    {
      clinicId: clinics[4].id,
      title: "Family Vaccination Package",
      titleAr: "باقة تطعيمات عائلية",
      description: "Complete vaccination package for the whole family",
      descriptionAr: "باقة تطعيمات شاملة للعائلة بأكملها",
      originalPrice: 200,
      discountedPrice: 140,
      pointsRequired: 1200,
      category: "تطعيمات",
      isFeatured: false,
      isActive: true,
      expiryDate: "2026-10-31",
      usageCount: 19,
    },
  ]);

  // Seed patients
  const patients = await db.insert(patientsTable).values([
    { name: "محمد بن علي الراشدي", phone: "+968 9912 3456", email: "mohammed@example.com", level: "silver", points: 1350, totalVisits: 8 },
    { name: "فاطمة الزهراء البلوشي", phone: "+968 9923 4567", email: "fatima@example.com", level: "gold", points: 4200, totalVisits: 22 },
    { name: "أحمد سالم الحارثي", phone: "+968 9934 5678", email: "ahmed@example.com", level: "bronze", points: 450, totalVisits: 3 },
    { name: "مريم خالد العمري", phone: "+968 9945 6789", email: "mariam@example.com", level: "platinum", points: 8900, totalVisits: 41 },
    { name: "سعيد ناصر الكندي", phone: "+968 9956 7890", email: "saeed@example.com", level: "silver", points: 1800, totalVisits: 11 },
    { name: "نور عبدالله المعمري", phone: "+968 9967 8901", email: "noor@example.com", level: "bronze", points: 200, totalVisits: 2 },
    { name: "عمر يوسف الرياضي", phone: "+968 9978 9012", email: "omar@example.com", level: "gold", points: 3600, totalVisits: 18 },
    { name: "هنا ماجد الصيني", phone: "+968 9989 0123", email: "hana@example.com", level: "silver", points: 2100, totalVisits: 14 },
  ]).returning();

  // Seed appointments
  await db.insert(appointmentsTable).values([
    {
      patientName: "محمد بن علي الراشدي",
      patientPhone: "+968 9912 3456",
      clinicId: clinics[0].id,
      clinicName: "مركز أحمد الصالح الطبي",
      service: "General Checkup",
      serviceAr: "فحص عام",
      date: "2026-03-15",
      time: "10:00",
      status: "confirmed",
      pointsEarned: 150,
    },
    {
      patientName: "فاطمة الزهراء البلوشي",
      patientPhone: "+968 9923 4567",
      clinicId: clinics[1].id,
      clinicName: "عيادة الشفاء للأسنان",
      service: "Teeth Cleaning",
      serviceAr: "تنظيف الأسنان",
      date: "2026-03-16",
      time: "14:00",
      status: "pending",
      pointsEarned: 0,
    },
    {
      patientName: "مريم خالد العمري",
      patientPhone: "+968 9945 6789",
      clinicId: clinics[3].id,
      clinicName: "معهد عيون عُمان",
      service: "Eye Examination",
      serviceAr: "فحص العيون",
      date: "2026-03-10",
      time: "09:30",
      status: "completed",
      pointsEarned: 180,
    },
    {
      patientName: "أحمد سالم الحارثي",
      patientPhone: "+968 9934 5678",
      clinicId: clinics[4].id,
      clinicName: "عيادة ويلنس العائلية",
      service: "Family Consultation",
      serviceAr: "استشارة عائلية",
      date: "2026-03-20",
      time: "11:00",
      status: "pending",
      pointsEarned: 0,
    },
    {
      patientName: "سعيد ناصر الكندي",
      patientPhone: "+968 9956 7890",
      clinicId: clinics[2].id,
      clinicName: "مركز رويال للعلاج الطبيعي",
      service: "Physiotherapy Session",
      serviceAr: "جلسة علاج طبيعي",
      date: "2026-03-08",
      time: "16:00",
      status: "completed",
      pointsEarned: 200,
    },
    {
      patientName: "هنا ماجد الصيني",
      patientPhone: "+968 9989 0123",
      clinicId: clinics[0].id,
      clinicName: "مركز أحمد الصالح الطبي",
      service: "Blood Tests",
      serviceAr: "تحاليل الدم",
      date: "2026-03-18",
      time: "08:30",
      status: "confirmed",
      pointsEarned: 150,
    },
    {
      patientName: "عمر يوسف الرياضي",
      patientPhone: "+968 9978 9012",
      clinicId: clinics[1].id,
      clinicName: "عيادة الشفاء للأسنان",
      service: "Dental Implant",
      serviceAr: "زراعة الأسنان",
      date: "2026-02-28",
      time: "10:00",
      status: "completed",
      pointsEarned: 120,
    },
  ]);

  // Seed discounts
  await db.insert(discountsTable).values([
    {
      code: "BRONZE10",
      title: "Bronze Member Discount",
      titleAr: "خصم العضو البرونزي",
      description: "10% discount for bronze members on all dental services",
      discountPercent: 10,
      requiredLevel: "bronze",
      clinicId: clinics[1].id,
      clinicName: "عيادة الشفاء للأسنان",
      service: "جميع خدمات الأسنان",
      expiryDate: "2026-12-31",
      isActive: true,
      usageCount: 15,
      maxUsage: 200,
    },
    {
      code: "SILVER15",
      title: "Silver Member Discount",
      titleAr: "خصم العضو الفضي",
      description: "15% discount for silver members on general checkups",
      discountPercent: 15,
      requiredLevel: "silver",
      clinicId: clinics[0].id,
      clinicName: "مركز أحمد الصالح الطبي",
      service: "الفحوصات العامة",
      expiryDate: "2026-09-30",
      isActive: true,
      usageCount: 28,
      maxUsage: 100,
    },
    {
      code: "GOLD20",
      title: "Gold Member Discount",
      titleAr: "خصم العضو الذهبي",
      description: "20% discount for gold members on physiotherapy sessions",
      discountPercent: 20,
      requiredLevel: "gold",
      clinicId: clinics[2].id,
      clinicName: "مركز رويال للعلاج الطبيعي",
      service: "جلسات العلاج الطبيعي",
      expiryDate: "2026-06-30",
      isActive: true,
      usageCount: 8,
      maxUsage: 50,
    },
    {
      code: "PLAT30",
      title: "Platinum Exclusive Discount",
      titleAr: "خصم البلاتيني الحصري",
      description: "30% discount for platinum members on all services",
      discountPercent: 30,
      requiredLevel: "platinum",
      clinicId: null,
      clinicName: null,
      service: "جميع الخدمات",
      expiryDate: "2026-12-31",
      isActive: true,
      usageCount: 3,
      maxUsage: 30,
    },
    {
      code: "EYE25",
      title: "Eye Care Discount",
      titleAr: "خصم العناية بالعيون",
      description: "25% discount on eye examinations for gold+ members",
      discountPercent: 25,
      requiredLevel: "gold",
      clinicId: clinics[3].id,
      clinicName: "معهد عيون عُمان",
      service: "فحوصات العيون",
      expiryDate: "2026-08-31",
      isActive: true,
      usageCount: 12,
      maxUsage: 80,
    },
  ]);

  console.log("✅ Database seeded successfully!");
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
